# News
News.attr_accessible :user_id, :for
scripts = ['Just caught a Angelfish. It looks divine!', 'Just caught a Arapaima. This thing is huge!', "Just caught a Arowana. I caught an arowana! It's the golden dragon fish! I", "Just caught a . wonder what it's worth...", "Just caught a Barbel Steed. That's funny...It looks more like a fish than a horse.", "Just caught a Bass. If I can catch a drummer, maybe I'll form a band!", 'Just caught a Bitterling. I wonder what makes this little guy so angry...', "Just caught a Bluegill. Don't worry I caught the rest of the fish, too!", "Just caught a Brook Trout. I guess that little guy's just trOUT of luck!", "Just caught a Catfish. I think I'll name it Whiskers...", 'Just caught a Cherry Salmon. It looks so PITiful! Get it? Pit? Oh, never mind.', "Just caught a Coelacanth. Would you look at that! A living fossil. I didn't know", 'Just caught a . they truly existed.', 'Just caught a Crawfish. Check out those pincers!', 'Just caught a Crucian Carp. Carpe diem!', 'Just caught a Dace. Daces wild!', "Just caught a Eel. I've been told they're rEELy tough to catch (I'm sorry).", 'Just caught a Freshwater Goby. Go me, goby!', "Just caught a Frog. Think I should kiss it? (Ew...it's all warty!)", "Just caught a Giant Catfish. I caught a giant catfish! (That's because I used a giant", 'Just caught a . mousefish as bait!', 'Just caught a Giant Snakehead. Yep! A giant snakehead. Who names these things?', "Just caught a Goldfish. It's worth its weight in...fish. Great.", 'Just caught a Guppy. He ate an awful lot of bait for being so tiny!', 'Just caught a Jellyfish. I wonder how it would taste on some toast...', 'Just caught a Killifish. Killer!', 'Just caught a Koi. Whoever colored it did a real good job.', "Just caught a Large Bass. Well, it's pretty big...I guess...", "Just caught a Loach. You don't suppose it's Hylian, do you?", 'Just caught a Pale Chub. Looks like it could use a little sun...and a little diet', "Just caught a Piranha. I caught a piranha! Which river is this, anyway? I'm glad", "Just caught a . I didn't take a dip!", 'Just caught a Pond Smelt. Whew! And I thought the POND smelt bad!', 'Just caught a Popeyed Goldfish. Aw, look... He wants his spinach...', "Just caught a Rainbow Trout. Now that's a trout of a different color!", 'Just caught a Red Snapper. That was a snap! (I really have to stop saying things', 'Just caught a . like that.)', 'Just caught a Salmon. And it made it all the way back here!Now i feel bad.', 'Just caught a Sea Bass. See? Bass! (Why do I keep saying things like that?)', 'Just caught a Small Bass. Now, I just need to catch a small bass amp. (Oh, that was', 'Just caught a . terrible...)', 'Just caught a Stringfish. Ohhh, boy! I hooked a stringfish! I was just stringing it', 'Just caught a . along...', 'Just caught a Sweetfish. And let me tell you, that is one SWEET fish!'] # length=44

for i in 0..44
  story = {
    user_id: 1,
    title: "Exciting news!",
    body: scripts[i],
    for: 0
  }
  n = News.create(story)
  n.save
end
